import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(7,3))
ax.axis('off')
ax.text(0.02, 0.5, 'Left-eye fundus', va='center')
ax.annotate('', xy=(0.22,0.5), xytext=(0.08,0.5), arrowprops=dict(arrowstyle='->'))
ax.text(0.24, 0.5, 'RETFound encoder', va='center')
ax.annotate('', xy=(0.46,0.5), xytext=(0.36,0.5), arrowprops=dict(arrowstyle='->'))
ax.text(0.48, 0.5, 'DeepSurv head\n(log-risk)', va='center')
ax.annotate('', xy=(0.70,0.5), xytext=(0.60,0.5), arrowprops=dict(arrowstyle='->'))
ax.text(0.72, 0.5, 'Survival output\nS(t), risk@2/5y', va='center')
ax.set_title('Model pipeline')
fig.tight_layout()
fig.savefig('fig_pipeline.pdf')
print('Saved figures/fig_pipeline.pdf')